#!/usr/bin/env php
<?php

$loaderFile = array_reduce(
    [
        __DIR__ . '/../../autoload.php',
        __DIR__ . '/../vendor/autoload.php',
        __DIR__ . '/vendor/autoload.php'
    ],
    function ($carry, $item) {
        return file_exists($item) ? $item : $carry;
    }
);

/** @var \Composer\Autoload\ClassLoader $loader */
$loader = require($loaderFile);

// Register PSR-4 based loader on src dir
$loader->addPsr4('nisan\analyzer\\', __DIR__ . '/src');

$config = ['listSize' => 50];
if (!empty($argv[1])) {
    $config['dir'] = $argv[1];
}

(new \nisan\analyzer\Application($config))->run();
